name: Releases

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Conventional Changelog Action
        id: changelog
        if: env.HAS_TOKEN == 'true'
        uses: TriPSs/conventional-changelog-action@v5
        env:
          HAS_TOKEN: ${{ secrets.PA_TOKEN != '' }}
        with:
          github-token: ${{ secrets.PA_TOKEN }}
          version-file: './releases.json'

      - name: Create Release
        uses: actions/create-release@v1
        if: env.HAS_TOKEN == 'true' && steps.changelog.outputs.skipped == 'false'
        env:
          HAS_TOKEN: ${{ secrets.PA_TOKEN != '' }}
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
